[supabase]
url = "https://lgzuprcgcgyxcuaxwbxq.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnenVwcmNnY2d5eGN1YXh3YnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNjcyMDEsImV4cCI6MjA3Nzc0MzIwMX0.jrJeBYvaI-1YbIC5eIUW2U4fvNXiMdLCVmaF-Jj-0ZQ"
